name: godot-sl-car-rainbow-iqn-apex
channels:
    - pytorch
    - https://conda.anaconda.org/powerai
    - conda-forge
    - https://conda.anaconda.org/menpo
dependencies:
    - python==3.7.6
    - pip==20.0.2
    - conda-build
    - plotly==5.1.0
    - pytorch==1.9.0
    - pip:
        - matplotlib==3.1.3
        - gym==0.17.2
        - numpy==1.18.1
        - ffmpeg==1.4
        - opencv-python==4.5.2.54
        - redlock-py==1.0.8
